apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: kardasa
    provider: github
    repository: golang-pipeline-lab
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: kardasa-golang-pipeline-lab
  namespace: jx
spec:
  httpCloneURL: https://github.com/kardasa/golang-pipeline-lab.git
  org: kardasa
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: golang-pipeline-lab
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/kardasa/golang-pipeline-lab
