apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/environment/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-env-pr.yaml@versionStream
          resources: {}
        - name: make-pr
          resources: {}
        - image: ghcr.io/jenkins-x/jx-boot:3.2.188
          name: add-new-var
          resources: {}
          script: |
            #!/usr/bin/env sh
            echo Newly added step
            echo export MYVAR='foo' >> .jx/variables.sh
            cat .jx/variables.sh
        - image: ghcr.io/jenkins-x/jx-boot:3.2.188
          name: access-new-var
          resources: {}
          script: |
            #!/usr/bin/env sh
            echo newly added step
            source .jx/variables.sh
            cat .jx/variables.sh
            echo ${MYVAR}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
