apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: verify
    context: "verify"
    always_run: true
    optional: false
    source: "pullrequest.yaml"
    queries:
      - excludedBranches: { }
        included_branches: { }
        labels:
          entries:
            - approved
        milestone: ""
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
        review_approved_required: false
      - excludedBranches: { }
        included_branches: { }
        labels:
          entries:
            - env/staging
            - updatebot
        milestone: ""
        missingLabels:
          entries:
            - do-not-merge
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - needs-ok-to-test
            - needs-rebase
        review_approved_required: false

  - name: chuck
    context: "chuck"
    always_run: false
    optional: false
    skip_report: true
    trigger: "/jx chuck"
    rerun_command: "/jx chuck"
    source: "chuck.yaml"
  postsubmits:
  - name: bootjob
    context: "bootjob"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$
